// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaLrv6DH8dHsyeSK5JMgaJFLzg9eW2MlQ',
    appId: '1:366378803059:web:e207f7cffbc1192ff2ef06',
    messagingSenderId: '366378803059',
    projectId: 'appnotegk',
    authDomain: 'appnotegk.firebaseapp.com',
    storageBucket: 'appnotegk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt8fNw9Ko_eZHUFaOfFO3_1F8T15ZtFSY',
    appId: '1:366378803059:android:c26a9a64a196a28bf2ef06',
    messagingSenderId: '366378803059',
    projectId: 'appnotegk',
    storageBucket: 'appnotegk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaLrv6DH8dHsyeSK5JMgaJFLzg9eW2MlQ',
    appId: '1:366378803059:web:687e83c0fec82f42f2ef06',
    messagingSenderId: '366378803059',
    projectId: 'appnotegk',
    authDomain: 'appnotegk.firebaseapp.com',
    storageBucket: 'appnotegk.firebasestorage.app',
  );
}
